import { Button, Card, CardContent, CardHeader, CardTitle, Input } from '@dentivohq/ui';
import { useEffect, useState, type FormEvent } from 'react';
import { apiRequest } from '../lib/api';

type Patient = { id: string; displayName: string; email: string; phone: string; active: boolean };
export function PatientManagement({ clinicId, onClose }: { clinicId: string; onClose: () => void }) {
  const [patients, setPatients] = useState<Patient[]>([]); const [query, setQuery] = useState(''); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [message, setMessage] = useState('');
  async function load(search = query, targetPage = page) { const response = await apiRequest<{ data: Array<Record<string, unknown>>; meta: { total: number } }>(`/api/v1/clinics/${clinicId}/patients?query=${encodeURIComponent(search)}&page=${targetPage}&pageSize=20`); setPatients(response.data.map((row) => ({ id: String(row.id), displayName: String(row.display_name), email: String(row.email ?? ''), phone: String(row.phone ?? ''), active: Boolean(row.active) }))); setTotal(response.meta.total); }
  useEffect(() => {
    const controller = new AbortController(); const search = query;
    void apiRequest<{ data: Array<Record<string, unknown>>; meta: { total: number } }>(`/api/v1/clinics/${clinicId}/patients?query=${encodeURIComponent(search)}&page=${page}&pageSize=20`, { signal: controller.signal }).then((response) => { setPatients(response.data.map((row) => ({ id: String(row.id), displayName: String(row.display_name), email: String(row.email ?? ''), phone: String(row.phone ?? ''), active: Boolean(row.active) }))); setTotal(response.meta.total); }).catch((error: Error) => { if (error.name !== 'AbortError') setMessage(error.message); });
    return () => controller.abort();
  }, [clinicId, page, query]);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = Object.fromEntries(new FormData(event.currentTarget)); await apiRequest(`/api/v1/clinics/${clinicId}/patients`, { method: 'POST', body: JSON.stringify({ displayName: form.name, email: form.email || undefined, phone: form.phone || undefined }) }); event.currentTarget.reset(); await load(); }
  async function toggle(patient: Patient) { await apiRequest(`/api/v1/clinics/${clinicId}/patients/${patient.id}`, { method: 'PATCH', body: JSON.stringify({ active: !patient.active }) }); await load(); }
  async function edit(patient: Patient) { const displayName = window.prompt('Patient name', patient.displayName)?.trim(); if (!displayName) return; await apiRequest(`/api/v1/clinics/${clinicId}/patients/${patient.id}`, { method: 'PATCH', body: JSON.stringify({ displayName }) }); await load(); }
  return <main className="mx-auto w-full max-w-5xl px-4 py-7"><div className="mb-5 flex items-center justify-between"><div><h1 className="text-2xl font-extrabold">Patients</h1><p className="text-sm text-muted-foreground">Search, update, archive, or reactivate tenant-scoped patient records.</p></div><Button onClick={onClose} variant="outline">Back to dashboard</Button></div><Card className="mb-5"><CardHeader><CardTitle>Add patient</CardTitle></CardHeader><CardContent><form className="grid gap-3 sm:grid-cols-4" onSubmit={(event) => void create(event)}><Input aria-label="Patient name" name="name" placeholder="Full name" required /><Input aria-label="Patient email" name="email" placeholder="Email" type="email" /><Input aria-label="Patient phone" name="phone" placeholder="Phone" /><Button type="submit">Add</Button></form></CardContent></Card><form className="mb-4 flex gap-2" onSubmit={(event) => { event.preventDefault(); setPage(1); void load(query, 1); }}><Input aria-label="Search patients" onChange={(event) => setQuery(event.target.value)} placeholder="Search name, email, or phone" value={query} /><Button type="submit" variant="outline">Search</Button></form>{message ? <p role="alert">{message}</p> : null}<div className="grid gap-3">{patients.map((patient) => <Card key={patient.id}><CardContent className="flex items-center justify-between gap-3 p-4"><div><strong>{patient.displayName}</strong><p className="text-sm text-muted-foreground">{patient.email || 'No email'} · {patient.phone || 'No phone'} · {patient.active ? 'Active' : 'Archived'}</p></div><div className="flex gap-2"><Button onClick={() => void edit(patient)} variant="outline">Details / edit</Button><Button onClick={() => void toggle(patient)} variant="outline">{patient.active ? 'Archive' : 'Reactivate'}</Button></div></CardContent></Card>)}</div><div className="mt-4 flex items-center justify-between"><Button disabled={page === 1} onClick={() => setPage((value) => value - 1)} variant="outline">Previous</Button><span className="text-sm text-muted-foreground">Page {page} · {total} patient(s)</span><Button disabled={page * 20 >= total} onClick={() => setPage((value) => value + 1)} variant="outline">Next</Button></div></main>;
}
