import { Button, Card, CardContent, CardHeader, CardTitle, Input } from '@dentivohq/ui';
import { useEffect, useState, type FormEvent } from 'react';
import { apiRequest } from '../lib/api';

type Row = Record<string, unknown>; type Option = { id: string; name: string };
export function ScheduleManagement({ clinicId, onClose }: { clinicId: string; onClose: () => void }) {
  const [rules, setRules] = useState<{ schedules: Row[]; exceptions: Row[]; timeOff: Row[] }>({ schedules: [], exceptions: [], timeOff: [] }); const [dentists, setDentists] = useState<Option[]>([]); const [locations, setLocations] = useState<Option[]>([]); const [message, setMessage] = useState('');
  async function load() { const [ruleResponse, dentistResponse, locationResponse] = await Promise.all([apiRequest<{ data: typeof rules }>(`/api/v1/clinics/${clinicId}/scheduling-rules`), apiRequest<{ data: Row[] }>(`/api/v1/clinics/${clinicId}/dentists`), apiRequest<{ data: Row[] }>(`/api/v1/clinics/${clinicId}/locations`)]); setRules(ruleResponse.data); setDentists(dentistResponse.data.filter((row) => row.active).map((row) => ({ id: String(row.id), name: String(row.display_name) }))); setLocations(locationResponse.data.filter((row) => row.active).map((row) => ({ id: String(row.id), name: String(row.name) }))); }
  useEffect(() => {
    const controller = new AbortController();
    void Promise.all([apiRequest<{ data: typeof rules }>(`/api/v1/clinics/${clinicId}/scheduling-rules`, { signal: controller.signal }), apiRequest<{ data: Row[] }>(`/api/v1/clinics/${clinicId}/dentists`, { signal: controller.signal }), apiRequest<{ data: Row[] }>(`/api/v1/clinics/${clinicId}/locations`, { signal: controller.signal })]).then(([ruleResponse, dentistResponse, locationResponse]) => { setRules(ruleResponse.data); setDentists(dentistResponse.data.filter((row) => row.active).map((row) => ({ id: String(row.id), name: String(row.display_name) }))); setLocations(locationResponse.data.filter((row) => row.active).map((row) => ({ id: String(row.id), name: String(row.name) }))); }).catch((error: Error) => { if (error.name !== 'AbortError') setMessage(error.message); });
    return () => controller.abort();
  }, [clinicId]);
  async function create(event: FormEvent<HTMLFormElement>, kind: 'schedules' | 'schedule-exceptions' | 'time-off') { event.preventDefault(); const form = Object.fromEntries(new FormData(event.currentTarget)); let body: Record<string, unknown>; if (kind === 'schedules') body = { dentistId: form.dentistId, locationId: form.locationId, dayOfWeek: Number(form.dayOfWeek), startsAtLocal: form.startsAtLocal, endsAtLocal: form.endsAtLocal }; else if (kind === 'schedule-exceptions') body = { dentistId: form.dentistId, locationId: form.locationId, exceptionDate: form.exceptionDate, unavailable: true, reason: form.reason || undefined }; else body = { dentistId: form.dentistId, startsAt: new Date(String(form.startsAt)).toISOString(), endsAt: new Date(String(form.endsAt)).toISOString(), reason: form.reason || undefined }; await apiRequest(`/api/v1/clinics/${clinicId}/${kind}`, { method: 'POST', body: JSON.stringify(body) }); event.currentTarget.reset(); await load(); }
  async function remove(kind: string, id: unknown) { await apiRequest(`/api/v1/clinics/${clinicId}/${kind}/${String(id)}`, { method: 'DELETE' }); await load(); }
  async function editSchedule(row: Row) { const startsAtLocal = window.prompt('Start time (HH:MM)', String(row.starts_at_local).slice(0, 5)); if (!startsAtLocal) return; await apiRequest(`/api/v1/clinics/${clinicId}/schedules/${String(row.id)}`, { method: 'PATCH', body: JSON.stringify({ startsAtLocal }) }); await load(); }
  const options = <>{dentists.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</>; const locationOptions = <>{locations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</>;
  return <main className="mx-auto w-full max-w-6xl px-4 py-7"><div className="mb-5 flex items-center justify-between"><div><h1 className="text-2xl font-extrabold">Schedules & time off</h1><p className="text-sm text-muted-foreground">Manage every input used to calculate availability.</p></div><Button onClick={onClose} variant="outline">Back to dashboard</Button></div>{message ? <p role="alert">{message}</p> : null}<div className="grid gap-4 lg:grid-cols-3">
    <RuleCard title="Recurring schedule"><form className="grid gap-2" onSubmit={(event) => void create(event, 'schedules')}><Select name="dentistId">{options}</Select><Select name="locationId">{locationOptions}</Select><Select name="dayOfWeek">{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((day, index) => <option key={day} value={index}>{day}</option>)}</Select><Input aria-label="Start time" name="startsAtLocal" required type="time" /><Input aria-label="End time" name="endsAtLocal" required type="time" /><Button type="submit">Add schedule</Button></form>{rules.schedules.map((row) => <RuleRow key={String(row.id)} label={`Day ${row.day_of_week}: ${String(row.starts_at_local).slice(0,5)}–${String(row.ends_at_local).slice(0,5)}`} onEdit={() => void editSchedule(row)} onRemove={() => void remove('schedules', row.id)} />)}</RuleCard>
    <RuleCard title="Date exception"><form className="grid gap-2" onSubmit={(event) => void create(event, 'schedule-exceptions')}><Select name="dentistId">{options}</Select><Select name="locationId">{locationOptions}</Select><Input aria-label="Exception date" name="exceptionDate" required type="date" /><Input aria-label="Reason" name="reason" placeholder="Reason" /><Button type="submit">Block date</Button></form>{rules.exceptions.map((row) => <RuleRow key={String(row.id)} label={`${row.exception_date}: ${row.reason ?? 'Unavailable'}`} onRemove={() => void remove('schedule-exceptions', row.id)} />)}</RuleCard>
    <RuleCard title="Time off"><form className="grid gap-2" onSubmit={(event) => void create(event, 'time-off')}><Select name="dentistId">{options}</Select><Input aria-label="Time off starts" name="startsAt" required type="datetime-local" /><Input aria-label="Time off ends" name="endsAt" required type="datetime-local" /><Input aria-label="Reason" name="reason" placeholder="Reason" /><Button type="submit">Add time off</Button></form>{rules.timeOff.map((row) => <RuleRow key={String(row.id)} label={`${new Date(String(row.starts_at)).toLocaleString()} · ${row.reason ?? 'Time off'}`} onRemove={() => void remove('time-off', row.id)} />)}</RuleCard>
  </div></main>;
}
function Select({ children, name }: { children: React.ReactNode; name: string }) { return <select className="h-10 rounded-lg border border-border bg-background px-3" name={name} required><option value="">Select…</option>{children}</select>; }
function RuleCard({ children, title }: { children: React.ReactNode; title: string }) { return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent className="grid gap-4">{children}</CardContent></Card>; }
function RuleRow({ label, onEdit, onRemove }: { label: string; onEdit?: () => void; onRemove: () => void }) { return <div className="rounded-lg border border-border p-3 text-sm"><p className="mb-2">{label}</p><div className="flex gap-2">{onEdit ? <Button onClick={onEdit} size="sm" variant="outline">Edit</Button> : null}<Button onClick={onRemove} size="sm" variant="outline">Remove</Button></div></div>; }
