import { Button, Card, CardContent, CardHeader, CardTitle, Input } from '@dentivohq/ui';
import { useEffect, useState, type FormEvent } from 'react';
import { apiRequest } from '../lib/api';

type Service = { id: string; name: string; durationMinutes: number; priceMinor: number | null; currency: string | null; active: boolean };
export function ServiceManagement({ clinicId, onClose }: { clinicId: string; onClose: () => void }) {
  const [services, setServices] = useState<Service[]>([]); const [message, setMessage] = useState('');
  async function load() { const response = await apiRequest<{ data: Array<Record<string, unknown>> }>(`/api/v1/clinics/${clinicId}/services`); setServices(response.data.map((row) => ({ id: String(row.id), name: String(row.name), durationMinutes: Number(row.duration_minutes), priceMinor: row.price_minor == null ? null : Number(row.price_minor), currency: row.currency == null ? null : String(row.currency), active: Boolean(row.active) }))); }
  useEffect(() => {
    const controller = new AbortController();
    void apiRequest<{ data: Array<Record<string, unknown>> }>(`/api/v1/clinics/${clinicId}/services`, { signal: controller.signal }).then((response) => setServices(response.data.map((row) => ({ id: String(row.id), name: String(row.name), durationMinutes: Number(row.duration_minutes), priceMinor: row.price_minor == null ? null : Number(row.price_minor), currency: row.currency == null ? null : String(row.currency), active: Boolean(row.active) })))).catch((error: Error) => { if (error.name !== 'AbortError') setMessage(error.message); });
    return () => controller.abort();
  }, [clinicId]);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const price = String(form.get('price')).trim(); await apiRequest(`/api/v1/clinics/${clinicId}/services`, { method: 'POST', body: JSON.stringify({ name: form.get('name'), durationMinutes: Number(form.get('duration')), priceMinor: price ? Math.round(Number(price) * 100) : undefined, currency: price ? String(form.get('currency')).toUpperCase() : undefined }) }); event.currentTarget.reset(); await load(); }
  async function toggle(service: Service) { await apiRequest(`/api/v1/clinics/${clinicId}/services/${service.id}`, { method: 'PATCH', body: JSON.stringify({ active: !service.active }) }); await load(); }
  async function edit(service: Service) { const name = window.prompt('Service name', service.name)?.trim(); if (!name) return; await apiRequest(`/api/v1/clinics/${clinicId}/services/${service.id}`, { method: 'PATCH', body: JSON.stringify({ name }) }); await load(); }
  return <main className="mx-auto w-full max-w-5xl px-4 py-7"><div className="mb-5 flex items-center justify-between"><div><h1 className="text-2xl font-extrabold">Services</h1><p className="text-sm text-muted-foreground">Only active services are available for booking.</p></div><Button onClick={onClose} variant="outline">Back to dashboard</Button></div><Card className="mb-5"><CardHeader><CardTitle>Add service</CardTitle></CardHeader><CardContent><form className="grid gap-3 sm:grid-cols-5" onSubmit={(event) => void create(event)}><Input aria-label="Service name" name="name" placeholder="Consultation" required /><Input aria-label="Duration in minutes" min="5" name="duration" placeholder="Minutes" required type="number" /><Input aria-label="Price" min="0" name="price" placeholder="Price" step="0.01" type="number" /><Input aria-label="Currency" defaultValue="USD" maxLength={3} name="currency" /><Button type="submit">Add</Button></form></CardContent></Card>{message ? <p role="alert">{message}</p> : null}<div className="grid gap-3">{services.map((service) => <Card key={service.id}><CardContent className="flex items-center justify-between gap-3 p-4"><div><strong>{service.name}</strong><p className="text-sm text-muted-foreground">{service.durationMinutes} min · {service.priceMinor == null ? 'No price' : `${service.currency} ${(service.priceMinor / 100).toFixed(2)}`} · {service.active ? 'Active' : 'Archived'}</p></div><div className="flex gap-2"><Button onClick={() => void edit(service)} variant="outline">Edit</Button><Button onClick={() => void toggle(service)} variant="outline">{service.active ? 'Archive' : 'Reactivate'}</Button></div></CardContent></Card>)}</div></main>;
}
